name = "lambda_calculus_lean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LambdaCalculusLean"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[require]]
name = "mathlib_extra_lean"
git = "https://github.com/pthomas505/mathlib_extra_lean.git"
rev = "main"

[[lean_lib]]
name = "LambdaCalculusLean"
globs = ["LambdaCalculusLean.+"]
